#!/bin/sh
#
# @name Emesent Hovermap
#
# @type Quadrotor x
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=emesent}

param set-default SIM_GZ_EN 1

param set-default COM_OF_LOSS_T 3

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# Rotors
# SDF and Airframe have different reference frames!
param set-default CA_ROTOR0_PX  0.24
param set-default CA_ROTOR0_PY  0.24
param set-default CA_ROTOR0_KM  0.05 # CCW

param set-default CA_ROTOR1_PX -0.24
param set-default CA_ROTOR1_PY -0.24
param set-default CA_ROTOR1_KM  0.05 # CCW

param set-default CA_ROTOR2_PX  0.24
param set-default CA_ROTOR2_PY -0.24
param set-default CA_ROTOR2_KM -0.05 # CW

param set-default CA_ROTOR3_PX -0.24
param set-default CA_ROTOR3_PY  0.24
param set-default CA_ROTOR3_KM -0.05 # CW

# Set actuators to some functions
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

# Min-Max throttle values
param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

# Throttle % needed to hover
param set-default MPC_THR_HOVER 0.60
